# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b69b351a71a92b5355e323fe4aac23fdff60427579af098e1c6568b825718f970d655dae701be5adc5fbf618ac7ea2a4adfb008bbf1a4633ac0ece5453a45a40

test:
  secret_key_base: e3eba88debcf384375d0c1b8e1b77e348b82d871a4df097db66b37df56543adcd6c9f05d436c097b172a028091a76d349e77d1bc7191e0a9bbe45234babfba21

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
